// src/components/Lyrics.svelte
<script lang="ts">
import QrContainer from "./QrContainer.svelte";

export let alternativeBackground: boolean;
export let url: string

</script>


<div>
    <h1>Caos</h1>
    <div class="qrContainer">
        <QrContainer bind:alternativeBackground {url}/>
    </div>

    <div>
        <p>De pronto todo cambia y ellos llaman a decirme <br/>
            Señor debe hacer, lo que solía hacer<br/>
            Y no se parece en nada a lo que usted viene<br/>
            Haciendo desde tiempo atrás, algún tiempo atrás<br/>
        </p>
        <p>Y hoy le llame a contarle que tengo respuestas<br/>
            A preguntas que no entiendo bien<br/>
            Hoy abri el agua caliente y luego la fría<br/>
            Y no sabe usted lo que encontré</p>
        <p>De pronto desespero pues dicen que el comunismo<br/>
            No esta nada bien, en la pelicula de ayer<br/>
            Si esto es Cuba o Venezuela<br/>
            o la Rusia setentera que vamos a hacer<br/>
            Nos bombardearan también?</p>
        <p>Y hoy le llame a contarle que tengo<br/>
            Respuestas a preguntas que no entiendo bien<br/>
            Hoy abrí el agua caliente y luego la fría<br/>
            Y no sabe usted lo que encontré<br/>
            Y hoy lei en Hotmail que Bill Gates me daria<br/>
            Un centavo por cada email que enviara<br/>
            Viajando en el bus oi opiniones y pues las robe<br/>
            Que más iba a hacer? Que más iba a hacer?</p>
        <p>De pronto Dios, de quienes claman<br/>
            Ser sus hijos se olvidó y aquí estoy yo<br/>
            Adoptado en un orfanato de ateos<br/>
            Me dejo y al salir me confesó</p>
        <p>Lo siento pero ya debo renunciar<br/>
            En ustedes confiare<br/>
            Para el mundo guiar</p>
        <p>Lo siento pero ya debe renunciar<br/>
            En nosotros confió ya para el mundo guiar</p>
        <p>De pronto Dios, de quienes claman<br/>
            Ser sus hijos se olvidó y aquí estoy yo<br/>
            Adoptado, en un orfanato de ateos me dejo<br/>
            Y aquí estoy yo...</p>
    </div>
</div>

<style>
    .qrContainer{
        width: 100%;
        display: flex;
        flex-direction: row;
        justify-content: center;
    }
</style>

// src/components/Lyrics.tsx
export default function Lyrics(props: { children: React.ReactElement }) {

    // Hardcoded lyrics for proof of concept
    const defaultTitle = "Caos"
    const defaultLyrics = (<div>
        <p>De pronto todo cambia y ellos llaman a decirme <br/>
            Señor debe hacer, lo que solía hacer<br/>
            Y no se parece en nada a lo que usted viene<br/>
            Haciendo desde tiempo atrás, algún tiempo atrás<br/>
        </p>
        <p>Y hoy le llame a contarle que tengo respuestas<br/>
            A preguntas que no entiendo bien<br/>
            Hoy abri el agua caliente y luego la fría<br/>
            Y no sabe usted lo que encontré</p>
        <p>De pronto desespero pues dicen que el comunismo<br/>
            No esta nada bien, en la pelicula de ayer<br/>
            Si esto es Cuba o Venezuela<br/>
            o la Rusia setentera que vamos a hacer<br/>
            Nos bombardearan también?</p>
        <p>Y hoy le llame a contarle que tengo<br/>
            Respuestas a preguntas que no entiendo bien<br/>
            Hoy abrí el agua caliente y luego la fría<br/>
            Y no sabe usted lo que encontré<br/>
            Y hoy lei en Hotmail que Bill Gates me daria<br/>
            Un centavo por cada email que enviara<br/>
            Viajando en el bus oi opiniones y pues las robe<br/>
            Que más iba a hacer? Que más iba a hacer?</p>
        <p>De pronto Dios, de quienes claman<br/>
            Ser sus hijos se olvidó y aquí estoy yo<br/>
            Adoptado en un orfanato de ateos<br/>
            Me dejo y al salir me confesó</p>
        <p>Lo siento pero ya debo renunciar<br/>
            En ustedes confiare<br/>
            Para el mundo guiar</p>
        <p>Lo siento pero ya debe renunciar<br/>
            En nosotros confió ya para el mundo guiar</p>
        <p>De pronto Dios, de quienes claman<br/>
            Ser sus hijos se olvidó y aquí estoy yo<br/>
            Adoptado, en un orfanato de ateos me dejo<br/>
            Y aquí estoy yo...</p>
    </div>)

    return (
        <div>
            <h1 className='mt-5 mb-3'>{defaultTitle}</h1>
            {props.children}
            {defaultLyrics}
        </div>
    )
}
