// src/components/Home.svelte
<script lang="ts">
    import get_mqtt_client from "../services/mqtt.js";
    import {buildHandheldUrl, buildTopic} from "../services/utils";
    import Lyrics from "./Lyrics.svelte";

    export let id: string;

    let alternativeBackground = false

    get_mqtt_client().then(client => {
        client.subscribe_topic(
            buildTopic(id),
            (pkt: { json: () => any; }) => {
                let parsed = pkt.json()
                if (parsed.note === "toggle-background") {
                    alternativeBackground = !alternativeBackground
                }
            })
    })
</script>

<div class={`home ${alternativeBackground ? "alternative-bg" : ""}`}>
        {#if alternativeBackground}
            <div class="alternative-bg-background"/>
        {/if}
    <Lyrics
        bind:alternativeBackground
        url={buildHandheldUrl(id)}
    />
    <div class="home__footer">
        <div class="can-can-bc">
            <a class={`${alternativeBackground ? "alternative-bg" : ""}`}
               href="https://www.youtube.com/@pichudequito/videos"
               target="_blank">Band:
                Can Can
                (Ecuador)</a>
        </div>
        <div class="github-link">
            <a class={`${alternativeBackground ? "alternative-bg" : ""}`}
               href="https://github.com/linomp/react-qr-mqtt"
               target="_blank"><i
                    class="fab fa-github"></i></a>
        </div>
    </div>

</div>

// src/Home.tsx
import React, {useState} from 'react'
import QRCode from 'react-qr-code';


import Lyrics from './Lyrics';

function Home(props: { id: string }) {
    const [alternativeBackground, setAlternativeBackground] = useState(false)

    return (<div className={`home ${alternativeBackground ? "alternative-bg" : ""}`}>
        {alternativeBackground && <div className="alternative-bg-background"/>}
        <Lyrics
            children={
                (<div style={{height: "auto", margin: "0 auto", maxWidth: 80, width: "100%"}}>
                    <QRCode
                        onClick={() => setAlternativeBackground(!alternativeBackground)}
                        size={256}
                        style={{height: "auto", maxWidth: "100%", width: "100%"}}
                        bgColor={alternativeBackground ? "#000000" : "#FFFFFF"}
                        fgColor={alternativeBackground ? "#FFFFFF" : "#000000"}
                        // TODO: build actual url, not just the id
                        value={props.id}
                        viewBox={`0 0 ${256} ${256}`}
                    />
                </div>)}/>
        <div className="home__footer">
            <div className="can-can-bc">
                <a className={`${alternativeBackground ? "alternative-bg" : ""}`}
                   href="https://www.youtube.com/@pichudequito/videos"
                   target="_blank">Band:
                    Can Can
                    (Ecuador)</a>
            </div>
            <div className="github-link">
                <a className={`${alternativeBackground ? "alternative-bg" : ""}`}
                   href="https://github.com/linomp/react-qr-mqtt"
                   target="_blank"><i
                    className="fab fa-github"></i></a>
            </div>
        </div>

    </div>);
}

export default Home
